[package]
name = "build_agent"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"
toml = "0.5"
hyper = "0.12"
futures = "*"
tokio = "*"
tokio-process = "0.2"
